title: "Mi sitio web sencillo"
description: "PÃ¡gina creada con Jekyll y GitHub Pages"
url: "https://Javier22914.github.io"
baseurl: "" 

theme: "minimal-mistakes-jekyll" 


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
